{{- if .Values.flagger.enabled }}
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ include "treats-portfolio.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "treats-portfolio.fullname" . }}
  autoscalerRef:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    name: {{ include "treats-portfolio.fullname" . }}
  service:
    port: {{ .Values.service.port }}
  {{- with .Values.flagger.analysis }}
  analysis:
    {{- toYaml . | nindent 4 }}
  {{- end}}
{{- end}}