kind: Service
apiVersion: serving.knative.dev/v1
metadata:
  name: {{ include "treats-portfolio.fullname" . }}
  labels:
  {{- include "treats-portfolio.labels" . | nindent 4 }}
  annotations:
    networking.knative.dev/httpOption: "redirected"
    serving.knative.dev/rolloutDuration: "{{ .Values.rolloutDuration }}"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: {{ .Values.minScale }}
      labels:
      {{- include "treats-portfolio.labels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 80
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 80