apiVersion: v1
kind: Service
metadata:
  name: {{ include "treats-portfolio.fullname" . }}
  labels:
    {{- include "treats-portfolio.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "treats-portfolio.selectorLabels" . | nindent 4 }}
