kind: pipeline
type: kubernetes
name: default

trigger:
  branch:
    exclude:
      - renovate/*

steps:
  - name: restore-cache-with-filesystem
    image: plugins/s3-cache
    pull: 'always'
    when:
      event:
        exclude:
          - tag
    volumes:
      - name: cache
        path: /usr/local/share/.cache
    settings:
      restore: true
      cache_key: '{{ .Repo.Name }}-{{ checksum "yarn.lock" }}'
      path-style: true
      endpoint: http://minio-home.minio.svc.cluster.local:9000
      bucket: insuusvenerati
      region: us-east-1
      filename: ${DRONE_REPO_NAME}.tar.gz
      mount:
        - './.cache'
        - './public'
        - '/usr/local/share/.cache'
        - './node_modules'
      access_key:
        from_secret: minio_access_key_id
      secret_key:
        from_secret: minio_secret_access_key

  - name: install
    image: node:lts-buster-slim
    volumes:
      - name: cache
        path: /usr/local/share/.cache
    commands:
      - yarn install --frozen-lockfile
    when:
      event:
        exclude:
          - tag
    depends_on:
      - restore-cache-with-filesystem

  - name: build
    image: node:lts-buster-slim
    commands:
      - yarn build
    when:
      event:
        exclude:
          - tag
    environment:
      DATO_API_TOKEN:
        from_secret: DATO_API_TOKEN
    depends_on:
      - install

  - name: rebuild-cache-with-filesystem
    image: plugins/s3-cache
    pull: 'always'
    volumes:
      - name: cache
        path: /usr/local/share/.cache
    when:
      event:
        exclude:
          - tag
    settings:
      rebuild: true
      path-style: true
      endpoint: http://minio-home.minio.svc.cluster.local:9000
      cache_key: '{{ .Repo.Name }}-{{ checksum "yarn.lock" }}'
      filename: ${DRONE_REPO_NAME}.tar.gz
      bucket: insuusvenerati
      region: us-east-1
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - './.cache'
        - './public'
        - '/usr/local/share/.cache'
        - './node_modules'
      access_key:
        from_secret: minio_access_key_id
      secret_key:
        from_secret: minio_secret_access_key
    depends_on:
      - install
      - build

  - name: Test Chrome
    image: cypress/included:7.1.0
    when:
      event:
        exclude:
          - tag
    commands:
      - cypress install
      - yarn test:e2e:ci-chrome
    environment:
      DATO_API_TOKEN:
        from_secret: DATO_API_TOKEN
    depends_on:
      - install
      - build

  - name: semantic-release
    image: stiforr/ci-tools:1
    pull: 'always'
    commands:
      - yarn semantic-release
    when:
      branch:
        - main
        - develop
      event:
        exclude:
          - pull_request
          - tag
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    depends_on:
      - build
      - 'Test Chrome'

volumes:
  - name: cache
    temp: {}

---
kind: pipeline
type: kubernetes
name: publish

depends_on:
  - default

trigger:
  event:
    include:
      - tag

steps:
  - name: restore-cache-with-filesystem
    image: plugins/s3-cache
    pull: 'always'
    settings:
      restore: true
      cache_key: '{{ .Repo.Name }}-{{ checksum "yarn.lock" }}'
      path-style: true
      endpoint: http://minio-home.minio.svc.cluster.local:9000
      bucket: insuusvenerati
      region: us-east-1
      filename: ${DRONE_REPO_NAME}.tar.gz
      mount:
        - './public'
      access_key:
        from_secret: minio_access_key_id
      secret_key:
        from_secret: minio_secret_access_key

  - name: Helm Package
    image: stiforr/ci-tools:1
    pull: 'always'
    commands:
      - helm package k8s/treats-portfolio

  - name: Helm Push
    image: stiforr/ci-tools:1
    pull: 'always'
    commands:
      - /scripts/helm-push.sh
    depends_on:
      - 'Helm Package'
    environment:
      CHART_REPO_NAME:
        from_secret: CHART_REPO_NAME
      CHART_REPO_URL:
        from_secret: CHART_REPO_URL
      AWS_ACCESS_KEY_ID:
        from_secret: minio_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: minio_secret_access_key
      AWS_DEFAULT_REGION: us-east-1
      AWS_ENDPOINT: http://minio-home.minio.svc.cluster.local:9000
      AWS_DISABLE_SSL: 'true'

  - name: sentry-release
    image: stiforr/ci-tools:1
    pull: 'always'
    environment:
      SENTRY_PROJECT:
        from_secret: SENTRY_PROJECT
      SENTRY_AUTH_TOKEN:
        from_secret: SENTRY_AUTH_TOKEN
      SENTRY_ORG:
        from_secret: SENTRY_ORG
    commands:
      - /scripts/sentry-release.sh
    depends_on:
      - 'restore-cache-with-filesystem'

  - name: docker
    image: plugins/docker
    environment:
      DATO_API_TOKEN:
        from_secret: DATO_API_TOKEN
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: stiforr/treats-portfolio
      build_args_from_env:
        - DATO_API_TOKEN
      auto_tag: true
      tags:
        - latest
