kind: pipeline
type: docker
name: default

trigger:
  branch:
    exclude:
      - renovate/*

steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache:dev
    pull: 'always'
    settings:
      restore: true
      cache_key: '{{ .Repo.Name }}-{{ checksum "yarn.lock" }}'
      archive_format: 'gzip'
      bucket: stiforr-drone-cache
      region: us-east-1
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - '.cache'
        - 'public'
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    volumes:
      - name: cache
        path: /tmp/cache

  - name: install
    image: node:lts-buster-slim
    commands:
      - yarn install --frozen-lockfile
    when:
      branch:
        include:
          - main
          - develop
          - 'feature/*'
          - 'hotfix/*'
    depends_on:
      - restore-cache-with-filesystem

  - name: build
    image: node:lts-buster-slim
    commands:
      - yarn build
    when:
      branch:
        include:
          - main
          - develop
          - 'feature/*'
          - 'hotfix/*'
    environment:
      DATO_API_TOKEN:
        from_secret: DATO_API_TOKEN
      GATSBY_SENTRY_DSN:
        from_secret: GATSBY_SENTRY_DSN
    depends_on:
      - install

  - name: rebuild-cache-with-filesystem
    image: meltwater/drone-cache:dev
    pull: 'always'
    settings:
      rebuild: true
      cache_key: '{{ .Repo.Name }}-{{ checksum "yarn.lock" }}'
      archive_format: 'gzip'
      bucket: stiforr-drone-cache
      region: us-east-1
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - '.cache'
        - 'public'
    volumes:
      - name: cache
        path: /tmp/cache
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    depends_on:
      - install
      - build

  - name: Test Chrome
    image: cypress/included:7.1.0
    commands:
      - cypress install
      - yarn test:e2e:ci-chrome
    environment:
      DATO_API_TOKEN:
        from_secret: DATO_API_TOKEN
      GATSBY_SENTRY_DSN:
        from_secret: GATSBY_SENTRY_DSN
    depends_on:
      - install

  - name: deploy
    image: node:lts-buster-slim
    commands:
      - yarn global add firebase-tools firebase-ci
      - firebase-ci deploy
    environment:
      FIREBASE_TOKEN:
        from_secret: FIREBASE_TOKEN
    when:
      branch:
        - main
      event:
        exclude:
          - pull_request
          - tag
    depends_on:
      - build

  - name: semantic-release
    image: node
    commands:
      - yarn semantic-release
    when:
      branch:
        - main
        - develop
      event:
        exclude:
          - pull_request
          - tag
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    depends_on:
      - build
      - deploy
      - 'Test Chrome'

  - name: sentry-release
    image: stiforr/ci-tools:latest
    commands:
      - export SENTRY_RELEASE=$DRONE_TAG
      - export SENTRY_ENVIRONMENT=$(/scripts/environment.sh)
      - sentry-cli releases new $SENTRY_RELEASE -p $SENTRY_PROJECT
      - sentry-cli releases set-commits $SENTRY_RELEASE --auto
      - sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps ./public
      - sentry-cli releases finalize $SENTRY_RELEASE
      - sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT
    when:
      event:
        - tag

volumes:
  - name: cache
    host:
      path: /var/lib/cache
